/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const LOGOUT_USER = "LOGOUT_USER";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* HEALTH */
export const ADD_HEALTH = "ADD_HEALTH";
export const ADD_HEALTH_SUCCESS = "ADD_HEALTH_SUCCESS";
export const ADD_HEALTH_FAILURE = "ADD_HEALTH_FAILURE";

/* SYMPTOMS */
export const ADD_SYMPTOMS = "ADD_SYMPTOMS";
export const ADD_SYMPTOMS_SUCCESS = "ADD_SYMPTOMS_SUCCESS";
export const ADD_SYMPTOMS_FAILURE = "ADD_SYMPTOMS_FAILURE";

/* PARTNER */
export const ADD_PARTNER = "ADD_PARTNER";
export const ADD_PARTNER_SUCCESS = "ADD_PARTNER_SUCCESS";
export const ADD_PARTNER_FAILURE = "ADD_PARTNER_FAILURE";
export const PARTNER_GET_LIST = "PARTNER_GET_LIST";
export const PARTNER_GET_LIST_SUCCESS = "PARTNER_GET_LIST_SUCCESS";
export const PARTNER_GET_LIST_ERROR = "PARTNER_GET_LIST_ERROR";
export const PARTNER_GET_LIST_WITH_FILTER = "PARTNER_GET_LIST_WITH_FILTER";
export const PARTNER_GET_LIST_WITH_ORDER = "PARTNER_GET_LIST_WITH_ORDER";
export const PARTNER_GET_LIST_SEARCH = "PARTNER_GET_LIST_SEARCH";
export const PARTNER_ADD_ITEM = "PARTNER_ADD_ITEM";
export const PARTNER_ADD_ITEM_SUCCESS = "PARTNER_ADD_ITEM_SUCCESS";
export const PARTNER_ADD_ITEM_ERROR = "PARTNER_ADD_ITEM_ERROR";
export const PARTNER_SELECTED_ITEMS_CHANGE = "PARTNER_SELECTED_ITEMS_CHANGE";

/* DEPARTMENT */
export const DEPARTMENT_GET_LIST = "DEPARTMENT_GET_LIST";
export const DEPARTMENT_GET_LIST_SUCCESS = "DEPARTMENT_GET_LIST_SUCCESS";
export const DEPARTMENT_GET_LIST_ERROR = "DEPARTMENT_GET_LIST_ERROR";
export const DEPARTMENT_GET_LIST_WITH_FILTER = "DEPARTMENT_GET_LIST_WITH_FILTER";

/* PROVINCE */
export const PROVINCE_GET_LIST = "PROVINCE_GET_LIST";
export const PROVINCE_GET_LIST_SUCCESS = "PROVINCE_GET_LIST_SUCCESS";
export const PROVINCE_GET_LIST_ERROR = "PROVINCE_GET_LIST_ERROR";
export const PROVINCE_GET_LIST_WITH_FILTER = "PROVINCE_GET_LIST_WITH_FILTER";

/* DISTRICT */
export const DISTRICT_GET_LIST = "DISTRICT_GET_LIST";
export const DISTRICT_GET_LIST_SUCCESS = "DISTRICT_GET_LIST_SUCCESS";
export const DISTRICT_GET_LIST_ERROR = "DISTRICT_GET_LIST_ERROR";
export const DISTRICT_GET_LIST_WITH_FILTER = "DISTRICT_GET_LIST_WITH_FILTER";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./health/actions";
export * from "./symptoms/actions";
export * from "./ubigeo/actions";